### ISSUE TITLE
Jester respawn Jester bug still present

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jes#18]
Issue with winstate 5,  is still present, this bug break the round because i'm forced to slay the bugged Jester
it happend sometimes when a class "TEAM INNOCENT" kill the Jester
the Jester respawn Jester and he enters a loop
I have the last version of jester from github
i hope the fix will come soon 

[https://youtu.be/nj92ijAAap8](url)
(the video is a little bit old but the bug that i get is the same)

**Comment by Histalek** [comment]
To be more precise it happens when someone kills the Jester but only people of the killer's team (or none) have died. 
NOTE: it happens with all winstates where the jester respawns as an opposing role of the killer (1, 3 and 5 iirc)

I tried to fix it in the past, but wasn't able to completly solve the issue. Maybe i can spare a moment today or tomorrow and try my luck again
