### ISSUE TITLE
Wrong interaction between jester and infected

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jes#36]
Currently there is a bug that if the infected kills the jester, he dies (I have winstate 6), which should not be the case, since the infected should be able to kill the jester safely

**Comment by Histalek** [comment]
That is not really a bug, because winstate 6 only allows traitors and serialkillers to kill the jester without consequence.
But i agree with you that it doesn't make sense. The infected is supposed to kill people to get his 'zombies' and therefore he should be able to kill the jester. 
It would be quite easy to add the infected to the list, but as we are getting more and more roles i would think changing winstate 6 to "all players NOT in the innocent team can kill the jester without getting killed" seems more reasonable. 

What do you think?

**Comment by ThePlatinumGhost** [comment]
I reported the bug because in previous versions the infected did not die as soon as he killed the jester
the problem is that currently the infected person (which is practically a role that must "kill" everyone) cannot understand who the jester is.
He's in a hurry to kill everyone almost always ends up killing the jester and the ruond ends up in his role
therefore the solutions are in my opinion either to ensure that the role of the jester is visible to the infected, or to ensure that the infected kills the jester without problems
As for your idea, would the jester only annoy the innocent? while I honestly would prefer that it annoyed even the traitors
for example currently despite the fact that the traitors know who he is, he can throw himself into the crossfire of the traitors and fulfill his purpose
Thus killing a traitor and becoming the opposite role

**Comment by ThePlatinumGhost** [comment]
I searched the infected file for the thing I was looking for and found this
![inf](https://user-images.githubusercontent.com/36534723/76513627-e169e500-6456-11ea-8e07-f6814e6f3008.PNG)
[shouldn't this prevent the infected from dying if he kills the jester?]
(in https://github.com/TTT-2/ttt2-role_inf/blob/master/lua/terrortown/entities/roles/infected/shared.lua line 168)
that doesn't seem to work, I have a video that I did in the strange behavior that happens, that shouldn't happen
https://youtu.be/dTLN_UKyIow

**Comment by Histalek** [comment]
i have restored the jester interaction with the infected. Now the infected will prevent the jester winstates from taking effect (except winstate 1, in that case the jester still just wins if he gets killed).

I still very much like the idea of showing special roles who the jester is instead of them just being able to kill the jester. But for now this should suffice. thank you for reporting :)
